### ISSUE TITLE
Strawberry does not output any transcripts for our BAM file

### ISSUE THREAD

**Issue by lauraht** [ruolin/strawberry#21] opened 2018-07-29 13:14 UTC
Hello!

I tried to run strawberry in the default mode (no -g option) and with default parameters on the alignment BAM file generated by minimap2. The BAM file was sorted and they are single-end reads of a human sample. The strawberry output gtf file does not contain any transcripts (it is practically empty but only contains a comment line). There was no error message.

Based on the warnings in execution.log (such as unreasonable intron sizes either too long or too short, and filtering intron with only 1 read support), I added the following options:

--min-support-4-intron 1.0 -J 1000000 -j 20

But the strawberry output gtf file still does not contain any transcripts. And there was no error message. 

Does this mean Strawberry does not work with the alignment BAM file generated by minimap2?  What may be the reason of not working?

For strand information, minimap2 uses ts tags instead of XS tags. So we added XS tags in the minimap2 generated BAM file, so that our BAM file contains XS tags to indicate the strand properly. I'd assume Strawberry uses XS tags in the BAM file to identify the strand, right? 

I’d appreciate your advice very much.

I am also uploading tracking.log and execution.log here. 

Thank you very much!

[execution.log](https://github.com/ruolin/strawberry/files/2238788/execution.log)
[tracking.log](https://github.com/ruolin/strawberry/files/2238789/tracking.log)

**Comment by ruolin** [comment] 2018-07-30 23:09
@lauraht Thanks for reporting this problem. Currently Strawberry does not support single-end reads for denovo assembly. I am working on it right now to extend to single end reads.

**Comment by lauraht** [comment] 2018-07-31 12:55
Hi Ruolin,

Thank you so much for your response!

Great to know you are working on extending Strawberry to support single-end reads.

I was wondering if it might be possible to get a rough idea about the approximate time frame this may become available? I’d greatly appreciate it.

Thank you very much!

**Comment by ruolin** [comment] 2018-07-31 14:51
@lauraht Hi Lauraht. Thank you very much for your interest in Strawberry. I will try my best to make it available in a week.

**Comment by lauraht** [comment] 2018-08-01 04:22
Thanks a lot Ruolin!

**Comment by ruolin** [comment] 2018-08-03 06:26
@lauraht Actually, I just used Hista2 to align a single-end RNA-seq data. And Strawberry works fine. Do you mind sharing your data? I probably just need the first few thousand lines of your bam file.

**Comment by lauraht** [comment] 2018-08-03 10:15
Hi Ruolin,

Here is a sub-portion (first a few thousand lines) of our BAM file:
[sub_test.bam.gz](https://github.com/ruolin/strawberry/files/2256944/sub_test.bam.gz)

Thanks!

**Comment by ruolin** [comment] 2018-08-03 16:16
@lauraht Thanks I can reproduce your errors now. Are these pacbio ccs reads?

**Comment by lauraht** [comment] 2018-08-06 07:11
Yes.  Thanks!

**Comment by ruolin** [comment] 2018-08-08 02:05
@lauraht Hi the problem is not actually because of the single end. This is a work to extend Strawberry to third generation data. I am working on it right now. But it might take a little bit longer.

**Comment by ruolin** [comment] 2018-08-26 06:03
Hi @lauraht Sorry about the delay. Now I have added Pacbio ccs read support. Please check out https://github.com/ruolin/strawberry/releases/tag/1.0.1

**Comment by lauraht** [comment] 2018-08-26 15:49
Thank you very much Ruolin!

I will give it a try then.

**Comment by ruolin** [comment] 2018-08-26 23:56
Sure. Please let me know whether it works or not.

**Comment by lauraht** [comment] 2018-09-02 12:24
It works! Thanks Ruolin!

For Pacbio ccs reads, we'd better use "--min-support-4-intron 1.0" when running Strawberry, right?

**Comment by ruolin** [comment] 2018-09-02 16:10
I think I would actually use the default setting. Pacbio ccs is still less accurate than illumina, the splice alignment might not be good. However if you want supersensitive detection of transcripts, you can try 1. Based on the small test set, it seems to me the default is good. Do you have some ground truth so you can benchmark?

**Comment by lauraht** [comment] 2018-09-03 05:39
Thanks. 
I don't really have the ground truth. But by matching with transcripts in the human reference annotation, I found that using "--min-support-4-intron 1.0" Strawberry assembles relatively more correct transcripts (that match the reference transcripts) than using the default setting.

**Comment by ruolin** [comment] 2018-09-14 14:34
Thanks. That is good to know. I will close this issue for now.

**Closed as completed by ruolin** 2018-09-14 14:34 UTC
